This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./dissertation.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file dissertation.acn....done (16 entries accepted, 0 rejected).
Sorting entries....done (67 comparisons).
Generating output file dissertation.acr....done (42 lines written, 0 warnings).
Output written in dissertation.acr.
Transcript written in dissertation.alg.
