/* Se a relação for: PCEADMISSOES.INT_EPISODIO = PCEEPISODIOS.EPISODIO */
SELECT
  (SELECT COUNT(DISTINCT EPISODIO) FROM PCEEPISODIOS) AS TOTAL_EPISODIOS,
  (SELECT COUNT(DISTINCT INT_EPISODIO) 
     FROM PCEADMISSOES 
    WHERE INT_EPISODIO IS NOT NULL)                  AS EPISODIOS_COM_ADMISSAO,
  (
    SELECT COUNT(*)
    FROM (
      SELECT DISTINCT epi.EPISODIO
      FROM PCEEPISODIOS epi
      WHERE NOT EXISTS (
        SELECT 1
        FROM PCEADMISSOES adm
        WHERE adm.INT_EPISODIO = epi.EPISODIO
      )
    )
  )                                                  AS EPISODIOS_SEM_ADMISSAO
FROM DUAL;
