/* Funnel exclusivo: cada prescrição em EXACTAMENTE uma etapa */
WITH f AS (
  SELECT /*+ INDEX(f PRF_PRESC_MOV_FDET_IDPRESC_IDX) */ DISTINCT ID_PRESC
  FROM PCE.PRF_PRESC_MOV_FDET f
),
e AS (
  SELECT /*+ INDEX(e PRF_PRESC_MOV_ENF_001) */ DISTINCT ID_PRESC
  FROM PCE.PRF_PRESC_MOV_ENF e
),
class AS (
  SELECT
    p.ID_PRESC,
    CASE
      WHEN e.ID_PRESC IS NOT NULL THEN 'COM_ADMIN'
      WHEN f.ID_PRESC IS NOT NULL THEN 'DISP_SEM_ADMIN'
      WHEN p.DTA_VAL IS NOT NULL THEN 'VAL_SEM_DISP'
      ELSE 'PEND_VAL'
    END AS ETAPA
  FROM PCE.PRF_PRESC_MOV p
  LEFT JOIN f ON f.ID_PRESC = p.ID_PRESC
  LEFT JOIN e ON e.ID_PRESC = p.ID_PRESC
  /* Opcional: janela temporal para acelarar
     WHERE p.DTA_VAL >= ADD_MONTHS(TRUNC(SYSDATE), -12) */
),
agg AS (
  SELECT
    COUNT(*) AS TOTAL,
    SUM(CASE WHEN ETAPA='PEND_VAL'       THEN 1 ELSE 0 END) AS PEND_VAL,
    SUM(CASE WHEN ETAPA='VAL_SEM_DISP'   THEN 1 ELSE 0 END) AS VAL_SEM_DISP,
    SUM(CASE WHEN ETAPA='DISP_SEM_ADMIN' THEN 1 ELSE 0 END) AS DISP_SEM_ADMIN,
    SUM(CASE WHEN ETAPA='COM_ADMIN'      THEN 1 ELSE 0 END) AS COM_ADMIN
  FROM class
)
SELECT
  TOTAL,
  PEND_VAL,
  ROUND(PEND_VAL*100/NULLIF(TOTAL,0), 2)       AS PEND_VAL_PCT,
  VAL_SEM_DISP,
  ROUND(VAL_SEM_DISP*100/NULLIF(TOTAL,0), 2)   AS VAL_SEM_DISP_PCT,
  DISP_SEM_ADMIN,
  ROUND(DISP_SEM_ADMIN*100/NULLIF(TOTAL,0), 2) AS DISP_SEM_ADMIN_PCT,
  COM_ADMIN,
  ROUND(COM_ADMIN*100/NULLIF(TOTAL,0), 2)      AS COM_ADMIN_PCT
FROM agg;
