WITH f AS (SELECT DISTINCT ID_PRESC FROM PCE.PRF_PRESC_MOV_FDET),
     e AS (SELECT DISTINCT ID_PRESC FROM PCE.PRF_PRESC_MOV_ENF)
SELECT
  SUM(CASE WHEN p.DTA_VAL IS NULL AND f.ID_PRESC IS NOT NULL THEN 1 ELSE 0 END) AS DISPENSA_SEM_VALIDACAO,
  SUM(CASE WHEN p.DTA_VAL IS NULL AND e.ID_PRESC IS NOT NULL THEN 1 ELSE 0 END) AS ADMINISTRACAO_SEM_VALIDACAO,
  SUM(CASE WHEN e.ID_PRESC IS NOT NULL AND f.ID_PRESC IS NULL THEN 1 ELSE 0 END) AS ADMINISTRACAO_SEM_DISPENSA
FROM PCE.PRF_PRESC_MOV p
LEFT JOIN f ON f.ID_PRESC = p.ID_PRESC
LEFT JOIN e ON e.ID_PRESC = p.ID_PRESC;
